version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: online_store
    ports:
      - "8080:8080"
    command: -p 8080

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 8080
      DB_USER: store_user
      DB_PASSWORD: 123456
      DB_NAME: online_store
    command: ["/app/myserver", "0.0.0.0", "8081"]

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server

